apiVersion: v1
kind: Service
metadata:
  namespace: $namespace
  labels:
    version: v1
    app: ipex-eureka
  annotations:
    kubesphere.io/serviceType: statelessservice
  name: ipex-eureka
spec:
  ports:
    - name: tcp-7000
      protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: $NODEPORT
  selector:
    app: ipex-eureka
    version: v1
  sessionAffinity: None
  type: NodePort
